<a href="https://colab.research.google.com/github/SajanArik/CourseraDataScience/blob/main/Introduction_To_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import Numpy
import numpy as np

In [2]:
#Define List of Car Brands
arr_str = ["Mercedes","BMW", "Audi", "Ferrari","Tesla"]

#Define number of cylinders in car
arr_num = [5,3,6,7,3]

In [6]:
#Convert list arr_str to array
np_arr_str = np.array(arr_str)

#Convert list arr_num to array
np_arr_num = np.array(arr_num)

#Check Output
print("Numpy Array (arr_str): " ,np_arr_str)
print("Numpy Array (arr_num): " ,np_arr_num)

Numpy Array (arr_str):  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']
Numpy Array (arr_num):  [5 3 6 7 3]


In [8]:
#Check Data Type
print("Data type of arr_str: ", type(arr_str))
print("Data type of arr_num: ", type(arr_num))
#Check Data Type
print("Data type of np_arr_str: ", type(np_arr_str))
print("Data type of np_arr_num: ", type(np_arr_num))

Data type of arr_str:  <class 'list'>
Data type of arr_num:  <class 'list'>
Data type of np_arr_str:  <class 'numpy.ndarray'>
Data type of np_arr_num:  <class 'numpy.ndarray'>


In [11]:
#Create Matrix for multiple cyldinders
matrix = np.array([[1,2,1],[4,5,9],[1,8,9],])
print(matrix)

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [12]:
#Check Data Type
print("Data type of matrix: ", type(matrix))

Data type of matrix:  <class 'numpy.ndarray'>
